### ISSUE TITLE
Sem 2 Probablity Solutions for Sheldon's book: The current link stopped working

### ISSUE THREAD

**Issue by cuanim** [aflah02/SemWiseResourcesIIIT#19]
The current link leads to a `PAGE NOT FOUND`.  So here's an alternative:
`https://minerva.it.manchester.ac.uk/~saralees/statbook3.pdf`

**Comment by aflah02** [comment]
Oh thanks for the catch!
Interested in opening a PR?

**Comment by cuanim** [comment]
Done!
