### ISSUE TITLE
Tasty themed github.io page

### ISSUE THREAD

**Issue by Anindya-Prithvi** [aflah02/SemWiseResourcesIIIT#24]
- restructure readme to yaml
- spam <table><tr><td>
- add current README.md to CI/CD using GH actions

**Comment by aflah02** [comment]
Let's discuss this on Whatsapp

**Comment by aflah02** [comment]
SGTM
I'll take this up!

**Comment by Anindya-Prithvi** [comment]
Wonderful, please link the branch here, maybe i can drop in some stuff too lol
