### ISSUE TITLE
Migrating to MkDocs-Material 

### ISSUE THREAD

**Issue by Anirudh-S-Kumar** [aflah02/SemWiseResourcesIIIT#28]
The repository has grown unwieldy, and the Jekyll-generated website is just the README in a webpage format. I suggest that we migrate to [mkdocs-material](https://squidfunk.github.io/mkdocs-material/). 

This would result in the ditching of README.md and resources.yaml in favour of different markdown files for each semester. It would also remove the simplicity of just having everything in the README file, solely relying on the website instead.

**Comment by Anirudh-S-Kumar** [comment]
I have already made the necessary changes to my fork, just would need to setup the CI/CD properly for it to work, along with maybe some more cosmetic changes

**Comment by Anindya-Prithvi** [comment]
That looks pretty good however I was looking for the tables, is there a way to do that? because the landing page looks a bit bland.

One plus point is searching.

Possibly we could host pages with this specific branch too.

I am willing to retain README.md since one shouldn't have to go to another webpage to view what could have been shown on GH, and our current readme does a good job of summarisation.

**Comment by Anindya-Prithvi** [comment]
as for CI/CD, I think we would be able to generate semester specific MD using our YAML....

The original purpose of YAML was to have a "single thing to edit"→so currently one can just add a bullet point

**Comment by Anirudh-S-Kumar** [comment]
> That looks pretty good however I was looking for the tables, is there a way to do that? because the landing page looks a bit bland.

There is a way to do it, although IMO it should get a bit more cleaner than what is is currently, it could be something like 

| Semester | Courses |
| --- | --- |
| Semester 1 | IP HC HCI LA COM |

where all of them are links to their respective pages. 

>I am willing to retain README.md since one shouldn't have to go to another webpage to view what could have been shown on GH, and our current readme does a good job of summarisation.

We can keep both if that's the need.

As for CI/CD, I have written the yaml file for using mkdocs-material to compile the files and put them in a separate branch.

**Comment by aflah02** [comment]
I would also prefer keeping the README as well 
The discord bot also depends on it I guess but I do like the new look
Some thoughts - 
- Should we build this using the yaml? It would retain the single point of edit thingy. So all of this gets built as soon as someone edits the yaml which includes the course hyperlinks on the coverpage as well
- The search thing is really cool and it would be an awesome addition
- Since we are restructuring, we could probably add a department tag to courses. I've wanted to do this for a while but never went ahead with it
- Should we keep the single page layout alive somewhere too? Just for legacy reasons or for someone just wanting to take a stroll through all the courses

Do share your thoughts @Anirudh-S-Kumar @Anindya-Prithvi

**Comment by Anirudh-S-Kumar** [comment]
1. I do think having the single point of adding resources is very valuable, and the YAML system certainly provides more flexibility and less chance of mess-ups
2. I agree with adding department tags to courses. However, I am not 100% certain how it would be implemented. 
3. Single page layout could be kept alive in the README still, just that we each time a new commit will be done, both the docs and the README would have to be built, which is easy to do using github actions so it shouldn't be a problem

**Comment by Anirudh-S-Kumar** [comment]
Regarding how the tags could be set, we could use shields like this, do note for all ssh courses we could use same color tag

## IP <img src="https://img.shields.io/badge/CSE101-005B96">
## DC <img src="https://img.shields.io/badge/ECE111-F22068">
## IHCI <img src="https://img.shields.io/badge/DES102-00a56f">
## LA <img src="https://img.shields.io/badge/MTH100-ff7200">
## ISA <img src="https://img.shields.io/badge/SOC101-513533">
## FOB <img src="https://img.shields.io/badge/BIO101-8A2BE2">
## COM  <img src="https://img.shields.io/badge/COM101-FFFFFF">

**Comment by aflah02** [comment]
SGTM
For tags I can think of having one more field in the courses yaml and storing it there. 
@Anindya-Prithvi any other things you'd like added?
I think this is a good set of things to do. Since you already have implemented major chunks of it feel free to raise a PR once you're done
Thanks!

**Comment by Anindya-Prithvi** [comment]
having dept. will have an added complexity for courses which are offered in 2 departments (e.g. Robotics (cse/ece))

rest SGTM. Techtree v2

**Comment by Anirudh-S-Kumar** [comment]
@Anindya-Prithvi You can add multiple shields to specify them, like this 

## ML <img src="https://img.shields.io/badge/CSE343-005B96"> <img src="https://img.shields.io/badge/ECE1343-F22068">

**Comment by aflah02** [comment]
lol yeah a list of depts makes sense then
But i guess it would be a lot of effort as well
we could maybe add it later?

**Comment by aflah02** [comment]
or if you're up for it feel free to go ahead, no issues anyways

**Comment by Anirudh-S-Kumar** [comment]
Create PR #29

**Comment by aflah02** [comment]
@Anirudh-S-Kumar It seems like the actions are failing. Can you take a look?

**Comment by Anirudh-S-Kumar** [comment]
Looking into it

**Comment by aflah02** [comment]
Do I also need to turn off gh pages from settings? I guess so as the page is being rendered in the old format rn but not sure

**Comment by Anindya-Prithvi** [comment]
line 313: resources.yaml

square brackets must be in quotes; see other md links

**Comment by Anirudh-S-Kumar** [comment]
> Do I also need to turn off gh pages from settings? I guess so as the page is being rendered in the old format rn but not sure

@aflah02 You need to change the branch to the gh-pages one I think

**Comment by Anirudh-S-Kumar** [comment]
Ok I know why the page isn't being shown properly, it's because I have to create a YAML file for building the docs as well. This can simply be done by calling both yaml_to_readme and yamk_to_docs in the same YAML file

**Comment by aflah02** [comment]
This should work right?
Actions pass now but the webpage doesn't render correctly. Or it hasn't been updated not sure why
<img width="563" alt="image" src="https://github.com/aflah02/SemWiseResourcesIIIT/assets/72096386/90e73867-dcc0-4313-bc30-9b06b402d84e">

**Comment by Anirudh-S-Kumar** [comment]
I just mentioned what needs to be changed in the PR. Basically the files generated are not being committed to the repo, so they are not showing up on the site

**Comment by Anirudh-S-Kumar** [comment]
@aflah02 You would need to force run the main YAML file file again, and then the ci and page deployment ones, since that file is only triggered when there are changes in resources.yaml

**Comment by aflah02** [comment]
Yeah triggered it

**Comment by aflah02** [comment]
Seems to be working now, closing the issue
Thanks for the cool stuff!
