### ISSUE TITLE
Several links not working in README

### ISSUE THREAD

**Issue by Abhinav-Ujjawal** [aflah02/SemWiseResourcesIIIT#33]
The semester and subject links given in the README are not working.
Concerned Image:
![Image](https://github.com/aflah02/SemWiseResourcesIIIT/assets/97021908/b2324826-1a88-4d18-b64f-a3e3b95e24bc)

After clicking on Sem-1, this is the result:
<img width="960" alt="image" src="https://github.com/aflah02/SemWiseResourcesIIIT/assets/97021908/a793d444-ba12-40da-adf7-38b525cecf61">

I got similar results for others as well. This may be because of recent changes, but even FF (the subject I added yesterday) has the wrong link redirection.  I am unsure, but if the README is being changed automatically, I think we are putting the wrong redirecting link.

Example : 

- For IP, the link is: https://github.com/aflah02/SemWiseResourcesIIIT/blob/main/semester-1#ip
- For FF, it is: https://github.com/aflah02/SemWiseResourcesIIIT/blob/main/open-electives#ff

**Comment by Anirudh-S-Kumar** [comment]
Lemme look into this

**Comment by Anirudh-S-Kumar** [comment]
I've figured out the issue, making the PR

**Comment by aflah02** [comment]
Thanks!
