### ISSUE TITLE
Sir pls have mercy

### ISSUE THREAD

**Issue by Anindya-Prithvi** [aflah02/SemWiseResourcesIIIT#5]
Sir please see below image. Why bully sir. Unacceptable this is

<table><tr><td><img src="https://user-images.githubusercontent.com/29653551/150200821-e055721f-4dde-4616-b911-98fe0316845e.png" style="border: 10px solid black" /></td></tr></table>
😢 😭 😢 😭 😢 😭

**Comment by aflah02** [comment]
ffffffffffffffffffff
MY BAD
Pls make a PR :)

**Comment by Anindya-Prithvi** [comment]
@aflah02 please review https://github.com/aflah02/SemWiseResourcesIIIT/pull/6
Thanks.
